# Generated by Django 2.1.5 on 2019-01-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(null=True, upload_to='static/back/images/arclist'),
        ),
    ]
