# Generated by Django 2.1.5 on 2019-01-12 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_auto_20190112_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='kewords',
            new_name='keywords',
        ),
    ]
