# Generated by Django 2.1.5 on 2019-01-14 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_auto_20190112_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=10, unique=True)),
                ('another_name', models.CharField(max_length=10, unique=True)),
                ('c_describe', models.CharField(max_length=100)),
                ('c_keywords', models.CharField(max_length=10, null=True)),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.Column')),
            ],
            options={
                'db_table': 'tb_column',
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='a_colum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.Column'),
        ),
    ]
