# Generated by Django 2.1.5 on 2019-01-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_auto_20190114_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='c_keywords',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
