# Generated by Django 2.1.5 on 2019-01-16 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_auto_20190116_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='a_column',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='back.Column'),
        ),
    ]
