# Generated by Django 2.1.5 on 2019-01-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_auto_20190116_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='describe',
            field=models.CharField(max_length=255),
        ),
    ]
